apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  revisionHistoryLimit: {{ .Values.frontend.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      restartPolicy: {{ .Values.frontend.restart_policy }}
      containers:
      - image: {{ .Values.frontend.image }}
        name: frontend-container
        ports:
        - containerPort: 80
          name: http-port
        imagePullPolicy: Always
        livenessProbe:
            httpGet:
              path: /index.php
              port: http-port
            initialDelaySeconds: 40
            periodSeconds: 10
        readinessProbe:
            httpGet:
              path: /index.php
              port: http-port
            initialDelaySeconds: 40
            periodSeconds: 60
        
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-service
  name: frontend-service
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: {{ .Values.frontend.service_type }}

