apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secret_name }}
  namespace: {{ .Values.ingress.namespace }}
type: Opaque
data:
  tls.crt: {{ .Values.ingress.tls.crt }}
  tls.key: {{ .Values.ingress.tls.key }}


---

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: nginx-config
  namespace: {{ .Values.ingress.namespace }}
data:
